package App1904;
public class main {
	public static void main(String[] args) {
    Person ps=new Person(null,0);
    ps.nhapTen();
    ps.nhapTuoi();
    ps.inTenvaTuoi();
    Student st=new Student(null,0,null,0);
    st.nhapLop();
    st.nhapDtb();
    st.nhapTen();
    st.nhapTuoi();
    st.inTenvaTuoi();
    OfflineStudent off=new OfflineStudent(null,0,null,0,null);
    off.nhapTen();
    off.nhapTuoi();
    off.nhapLop();
    off.nhapDtb();
    off.nhapPhuongTien();
    off.inTenvaTuoi();
    OnlineStudent onl=new OnlineStudent(null,0,null,0,null);
    onl.nhapTen();
    onl.getLop();
    onl.nhapTuoi();
    onl.nhapDtb();
    onl.nhapPhuongTienHoc();
    onl.inTenvaTuoi();
    Employee ep=new Employee(null,0,null,0,0,0);
    ep.nhapTen();
    ep.nhapTuoi();
	ep.nhapTenCongTyLamViec();
	ep.nhapGioLamViec();
	ep.tinhLuong();
	ep.inTenvaTuoi();
    PartTimeEmployee pe=new PartTimeEmployee(null,0,null,0,0,0,0);
    pe.nhapTen();
    pe.nhapTuoi();
	pe.nhapTenCongTyLamViec();
	pe.nhapSoNgayLamViec();
	pe.nhapGioLamViec();
	pe.tinhLuong();
	pe.inTenvaTuoi();
    FullTimeEmployee fe=new FullTimeEmployee(null,0,null,0,0,0,0);
    fe.nhapTen();
    fe.nhapTuoi();
	fe.nhapTenCongTyLamViec();
	fe.nhapSoNgayLamViec();
	fe.nhapGioLamViec();
	fe.tinhLuong();
	fe.inTenvaTuoi();
    Customer cu=new Customer()(null,0,null,0);
    cu.nhapTen();
    cu.nhapTuoi();
    cu.nhapID();
    cu.inTenvaTuoi();
    VIPCustomer vip=new VIPCustomer(null,0,null,0);
    vip.nhapTen();
    vip.nhapTuoi();
    vip.nhapID();
    vip.inTenvaTuoi();
	}
}